### Create new category
POST http://localhost:3001/question-category/
Content-Type: application/json

{
  "data":{
    "category": "categoria 3"
  }
}

### Get all categories
GET http://localhost:3001/question-category/