### add questions to partner
POST http://localhost:3001/question-partner/
Content-Type: application/json

{
  "data":{
    "partnerId": 6,
    "questions": [
      {
      "questionId": 9,
      "online": true
    },
    {
      "questionId": 10,
      "online": false
    }
    ]
  }
}

### Get questions by partner
GET http://localhost:3001/question-partner/7