### Create new Question
POST http://localhost:3001/question/
Content-Type: application/json

{
  "data":{
    "question": "pregunta 3",
    "CategoryId": 2
  }
}

### Get all questtions by categories
GET http://localhost:3001/question/