### Create new review
POST http://localhost:3001/review/
Content-Type: application/json

{
  "data":{
    "PartnerId": 6,
    "StoreId": 1,
    "contactName": "raul",
    "date": "2021-01-01",
    "startTime": "10:40",
    "endTime": "12:40",
    "online": true,
    "type": "rutine",
    "rating": 5,
    "questions":[
      {
        "QuestionId": 9,
        "status": "correcto",
        "comments": "textito3",
        "plan": "textito4",
        "date": "2021-01-01",
        "breach": "textito5"
      }
    ]
  }
}


### Get all reviews
GET http://localhost:3001/review/


### Get all questions by partner and online
GET http://localhost:3001/review/questions/?partnerId=7&online=true