###
POST http://localhost:3001/user/
Content-Type: application/json

{
    "data": {
        "email": "jorgesalgado_dev@outlook.com",
        "password": "Brades123",
        "firstName": "Jorge Luis",
        "lastName": "Salgado Ledezma",       
        "nickname": "Jorge Salgado",
        "gender": "1",
        "userRole": "admin"
    }
}

###
GET http://localhost:3001/user/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvcmdlc2FsZ2Fkb19kZXZAb3V0bG9vay5jb20iLCJpZCI6MSwiaWF0IjoxNjgyNzk5NDY1LCJleHAiOjE2ODI4MTc0NjV9.2t5cnPP9rCcwc7C3J7eB4Wwx-2VLsRDlgCmO-xvxGAg

###
GET http://localhost:3001/user/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvcmdlc2FsZ2Fkb19kZXZAb3V0bG9vay5jb20iLCJpZCI6MSwiaWF0IjoxNjgyNzk5NDY1LCJleHAiOjE2ODI4MTc0NjV9.2t5cnPP9rCcwc7C3J7eB4Wwx-2VLsRDlgCmO-xvxGAg
###
DELETE http://localhost:3001/user/2

###
POST http://localhost:3001/auth/
Content-Type: application/json

{
    "data": {
        "email": "jorgesalgado_dev@outlook.com",
        "password": "Brades123"
    }
}
